import Head from 'next/head'
// import { Inter } from 'next/font/google'
import { client } from '../lib/client.js';
// const inter = Inter({ subsets: ['latin'] })
import { Product, FooterBanner, HeroBanner } from '../components';
export default function Home({ products, bannerData }) {
  return (
    <>
      <Head>
        <title>Create Next App You</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main >
       
       <HeroBanner heroBanner={bannerData.length && bannerData[0]}  />
    <div className="products-heading">
      <h2>Best Seller Products</h2>
      <p>speaker There are many variations passages</p>
    </div>
    <div className="products-container">
      {products?.map((product) => <Product key={product._id} product={product} />)}
    </div>


     <FooterBanner footerBanner={bannerData && bannerData[0]} />
      </main>
    </>
  )
}
export const getServerSideProps = async () => {
  const query = '*[_type == "product"]';
  const products = await client.fetch(query);

  const bannerQuery = '*[_type == "banner"]';
  const bannerData = await client.fetch(bannerQuery);

  return {
    props: { products, bannerData }
  }
}